package migrate

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/roboweaver/grimoire/internal/storage/rebind"
)

// SyncIdentitySequences realigns PostgreSQL identity sequences with the data
// actually present in the prefixed WordPress tables. It is a no-op on MySQL and
// SQLite.
//
// # Why this is needed
//
// The WordPress schema assigns explicit primary keys in places -- seeding writes
// post IDs 1 to 4 and user ID 1, a restored dump carries whatever ids it was
// taken with, and an overlay install inherits a table someone else populated.
// The three vendors disagree about what that does to the generator:
//
//   - MySQL advances AUTO_INCREMENT past any explicitly inserted value.
//   - SQLite derives the next INTEGER PRIMARY KEY from the current maximum rowid.
//   - PostgreSQL does neither. GENERATED BY DEFAULT AS IDENTITY lets an explicit
//     value through untouched and leaves the sequence where it was, so the next
//     generated id is 1.
//
// The consequence on PostgreSQL is not a subtle one: immediately after a
// successful seed, the first post or user created through the admin collides
// with seeded row 1 and fails with a duplicate-key error. Nothing warns first,
// because the seed itself succeeds.
//
// Call this after any write that supplies explicit primary keys.
//
// # How
//
// Identity columns are discovered from information_schema rather than listed
// here, so a new table or a new key column in a later migration is covered
// without this function being updated. For each one the sequence is set to the
// current maximum, or rewound to "1 not yet used" when the table is empty, so an
// empty table still starts at 1 rather than skipping it.
func SyncIdentitySequences(ctx context.Context, db *sql.DB, vendor, prefix string) error {
	if vendor != "postgres" {
		return nil
	}

	cols, err := identityColumns(ctx, db, prefix)
	if err != nil {
		return err
	}
	for _, c := range cols {
		// table and column are server-supplied metadata, not user input, and
		// are quoted for the embedded SELECT. pg_get_serial_sequence instead
		// takes them as text parameters, which is why they appear twice in
		// different forms.
		quotedTable := rebind.Ident(vendor, c.table)
		quotedCol := rebind.Ident(vendor, c.column)
		q := rebind.Rebind(vendor, `SELECT setval(
			pg_get_serial_sequence(?, ?),
			COALESCE((SELECT MAX(`+quotedCol+`) FROM `+quotedTable+`), 1),
			(SELECT MAX(`+quotedCol+`) FROM `+quotedTable+`) IS NOT NULL)`)
		if _, err := db.ExecContext(ctx, q, c.table, c.column); err != nil {
			return fmt.Errorf("migrate: sync identity sequence for %s.%s: %w", c.table, c.column, err)
		}
	}
	return nil
}

// identityColumn is one PostgreSQL identity column found in the target schema.
type identityColumn struct {
	table  string
	column string
}

// identityColumns lists the identity columns of base tables in the current
// schema whose names start with prefix.
func identityColumns(ctx context.Context, db *sql.DB, prefix string) ([]identityColumn, error) {
	const q = `SELECT c.table_name, c.column_name
FROM information_schema.columns c
JOIN information_schema.tables t
  ON t.table_schema = c.table_schema AND t.table_name = c.table_name
WHERE c.table_schema = current_schema()
  AND t.table_type = 'BASE TABLE'
  AND c.is_identity = 'YES'
  AND c.table_name LIKE $1 ESCAPE '\'
ORDER BY c.table_name, c.column_name`

	rows, err := db.QueryContext(ctx, q, likePrefix(prefix)+"%")
	if err != nil {
		return nil, fmt.Errorf("migrate: list identity columns: %w", err)
	}
	defer rows.Close()

	var out []identityColumn
	for rows.Next() {
		var c identityColumn
		if err := rows.Scan(&c.table, &c.column); err != nil {
			return nil, fmt.Errorf("migrate: list identity columns: %w", err)
		}
		out = append(out, c)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("migrate: list identity columns: %w", err)
	}
	return out, nil
}

// likePrefix escapes the LIKE metacharacters in a table prefix. This matters for
// every realistic prefix, because WordPress prefixes end in an underscore and a
// bare "_" in LIKE matches any single character -- so "wp_%" would also match a
// table belonging to a prefix like "wpx".
func likePrefix(prefix string) string {
	r := strings.NewReplacer(`\`, `\\`, `%`, `\%`, `_`, `\_`)
	return r.Replace(prefix)
}
