#!/bin/sh
# Compose GRIMOIRE_DATABASE_DSN at runtime from a mounted Podman secret.
#
# The DSN is a single string that embeds the password, so putting it in the
# config file or in a -e flag would leak the credential into the image, into
# `podman inspect`, and into shell history. Building it here keeps the password
# only in the container's own process environment, sourced from the same
# wp-db-password secret the WordPress and MySQL containers use.
#
# Set GRIMOIRE_DATABASE_DSN explicitly to bypass this entirely.
set -eu

SECRET_PATH=${GRIMOIRE_DB_PASSWORD_FILE:-/run/secrets/wp-db-password}

if [ -z "${GRIMOIRE_DATABASE_DSN:-}" ] && [ -f "$SECRET_PATH" ]; then
    db_pass=$(cat "$SECRET_PATH")

    # go-sql-driver's DSN grammar is not URL-encoded: a password containing
    # '@', '/' or ':' would be mis-parsed. The passwords generated by
    # podman-wordpress-pods.sh are deliberately stripped to alphanumerics, so
    # this is safe -- but fail loudly rather than connect to the wrong place if
    # that ever stops being true.
    case $db_pass in
        *[!A-Za-z0-9]*)
            echo "entrypoint: DB password contains characters that are unsafe in a" \
                 "go-sql-driver DSN; set GRIMOIRE_DATABASE_DSN explicitly instead." >&2
            exit 1
            ;;
    esac

    export GRIMOIRE_DATABASE_DSN="${GRIMOIRE_DB_USER:-wordpress}:${db_pass}@tcp(${GRIMOIRE_DB_ADDR:-wp-db-pod:3306})/${GRIMOIRE_DB_NAME:-wordpress}?parseTime=true&charset=utf8mb4"
fi

exec "$@"
