package phpass

import "testing"

// Genuine WordPress portable-hash vectors generated by the canonical phpass
// reference algorithm (iteration_count_log2 = 8, so the cost character is '6').
// These serve as an independent oracle: the algorithm that produced them is the
// public-domain phpass PasswordHash, not this package.
var vectors = []struct {
	password string
	hash     string
}{
	{"correct horse battery staple", "$P$6abcd1234y7zbjnd3hLLiE10LQSp4j0"},
	{"hunter2", "$P$6WXYZ7890QmrM8eXI0pZSYhKFDWsuF0"},
	{"admin", "$P$6Salt.AbCUzpPVIK9ZXMm5j8H0Tczx."},
	{"café☕", "$P$6uni.C0deqv90TMW9D1J797oqO3a/v/"},
	{"phpbb-pass", "$H$6phpBBsl1n7umtTAprbDW/is6SMiSb1"},
}

func TestVerifyKnownVectors(t *testing.T) {
	for _, v := range vectors {
		t.Run(v.hash, func(t *testing.T) {
			if !Verify(v.password, v.hash) {
				t.Fatalf("Verify(%q, %q) = false, want true", v.password, v.hash)
			}
		})
	}
}

func TestVerifyWrongPassword(t *testing.T) {
	for _, v := range vectors {
		t.Run(v.hash, func(t *testing.T) {
			if Verify(v.password+"x", v.hash) {
				t.Fatalf("Verify(wrong, %q) = true, want false", v.hash)
			}
		})
	}
}

func TestVerifyRejectsMalformed(t *testing.T) {
	bad := []string{
		"",
		"$2a$10$abcdefghijklmnopqrstuv",      // bcrypt, not phpass
		"$P$",                                // too short
		"$P$6short",                          // salt/hash too short
		"$Q$6abcd1234y7zbjnd3hLLiE10LQSp4j0", // unknown id
		"$P$0abcd1234y7zbjnd3hLLiE10LQSp4j0", // cost char '0' -> log2 too small
		"plaintext",
	}
	for _, h := range bad {
		t.Run(h, func(t *testing.T) {
			if Verify("anything", h) {
				t.Fatalf("Verify(_, %q) = true, want false", h)
			}
		})
	}
}

func TestIdentify(t *testing.T) {
	yes := []string{
		"$P$6abcd1234y7zbjnd3hLLiE10LQSp4j0",
		"$H$6phpBBsl1n7umtTAprbDW/is6SMiSb1",
	}
	no := []string{
		"",
		"$2y$10$abcdefghijklmnopqrstuv",
		"$P",
		"plaintext",
	}
	for _, h := range yes {
		if !Identify(h) {
			t.Fatalf("Identify(%q) = false, want true", h)
		}
	}
	for _, h := range no {
		if Identify(h) {
			t.Fatalf("Identify(%q) = true, want false", h)
		}
	}
}
