-- WordPress-compatible schema (PostgreSQL). MySQL types translated:
-- BIGINT(20) UNSIGNED AUTO_INCREMENT -> BIGSERIAL/BIGINT GENERATED; LONGTEXT/TEXT -> TEXT;
-- DATETIME -> TIMESTAMP; prefix-length indexes -> plain indexes.

CREATE TABLE IF NOT EXISTS {{prefix}}posts (
  "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_author BIGINT NOT NULL DEFAULT 0,
  post_date TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
  post_content TEXT NOT NULL,
  post_title TEXT NOT NULL,
  post_excerpt TEXT NOT NULL,
  post_status VARCHAR(20) NOT NULL DEFAULT 'publish',
  post_name VARCHAR(200) NOT NULL DEFAULT '',
  post_type VARCHAR(20) NOT NULL DEFAULT 'post'
);
CREATE INDEX IF NOT EXISTS {{prefix}}posts_type_status_date ON {{prefix}}posts (post_type, post_status, post_date, "ID");
CREATE INDEX IF NOT EXISTS {{prefix}}posts_post_name ON {{prefix}}posts (post_name);

CREATE TABLE IF NOT EXISTS {{prefix}}postmeta (
  meta_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL DEFAULT 0,
  meta_key VARCHAR(255) DEFAULT NULL,
  meta_value TEXT
);
CREATE INDEX IF NOT EXISTS {{prefix}}postmeta_post_id ON {{prefix}}postmeta (post_id);
CREATE INDEX IF NOT EXISTS {{prefix}}postmeta_meta_key ON {{prefix}}postmeta (meta_key);

CREATE TABLE IF NOT EXISTS {{prefix}}options (
  option_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  option_name VARCHAR(191) NOT NULL DEFAULT '',
  option_value TEXT NOT NULL,
  autoload VARCHAR(20) NOT NULL DEFAULT 'yes',
  CONSTRAINT {{prefix}}options_option_name UNIQUE (option_name)
);

CREATE TABLE IF NOT EXISTS {{prefix}}terms (
  term_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL DEFAULT '',
  slug VARCHAR(200) NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS {{prefix}}terms_slug ON {{prefix}}terms (slug);

CREATE TABLE IF NOT EXISTS {{prefix}}term_taxonomy (
  term_taxonomy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  term_id BIGINT NOT NULL DEFAULT 0,
  taxonomy VARCHAR(32) NOT NULL DEFAULT '',
  description TEXT NOT NULL,
  parent BIGINT NOT NULL DEFAULT 0,
  count BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT {{prefix}}term_taxonomy_term_id_taxonomy UNIQUE (term_id, taxonomy)
);
CREATE INDEX IF NOT EXISTS {{prefix}}term_taxonomy_taxonomy ON {{prefix}}term_taxonomy (taxonomy);

CREATE TABLE IF NOT EXISTS {{prefix}}term_relationships (
  object_id BIGINT NOT NULL DEFAULT 0,
  term_taxonomy_id BIGINT NOT NULL DEFAULT 0,
  term_order INT NOT NULL DEFAULT 0,
  PRIMARY KEY (object_id, term_taxonomy_id)
);
CREATE INDEX IF NOT EXISTS {{prefix}}term_relationships_ttid ON {{prefix}}term_relationships (term_taxonomy_id);

CREATE TABLE IF NOT EXISTS {{prefix}}users (
  "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_login VARCHAR(60) NOT NULL DEFAULT '',
  user_nicename VARCHAR(50) NOT NULL DEFAULT '',
  display_name VARCHAR(250) NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS {{prefix}}users_user_login ON {{prefix}}users (user_login);
