-- M2: user authentication columns, usermeta, and sessions (PostgreSQL).
-- Extends the minimal {{prefix}}users table created in 0001 and adds the
-- WordPress-compatible usermeta table plus grimoire's native sessions table.
--
-- Migration contract: this runs only against grimoire-provisioned schemas
-- (a fresh 0001 users table with four columns). Postgres supports ADD COLUMN
-- IF NOT EXISTS, so this is also safe if a superset of columns already exists;
-- {{prefix}}sessions is grimoire-native and created with IF NOT EXISTS.

ALTER TABLE {{prefix}}users ADD COLUMN IF NOT EXISTS user_pass VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE {{prefix}}users ADD COLUMN IF NOT EXISTS user_email VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE {{prefix}}users ADD COLUMN IF NOT EXISTS user_url VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE {{prefix}}users ADD COLUMN IF NOT EXISTS user_registered TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00';
ALTER TABLE {{prefix}}users ADD COLUMN IF NOT EXISTS user_activation_key VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE {{prefix}}users ADD COLUMN IF NOT EXISTS user_status INT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS {{prefix}}usermeta (
  umeta_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL DEFAULT 0,
  meta_key VARCHAR(255) DEFAULT NULL,
  meta_value TEXT
);
CREATE INDEX IF NOT EXISTS {{prefix}}usermeta_user_id ON {{prefix}}usermeta (user_id);
CREATE INDEX IF NOT EXISTS {{prefix}}usermeta_meta_key ON {{prefix}}usermeta (meta_key);

CREATE TABLE IF NOT EXISTS {{prefix}}sessions (
  id VARCHAR(64) PRIMARY KEY,
  user_id BIGINT NOT NULL DEFAULT 0,
  csrf_token VARCHAR(64) NOT NULL DEFAULT '',
  created TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
  expires TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00'
);
CREATE INDEX IF NOT EXISTS {{prefix}}sessions_expires ON {{prefix}}sessions (expires);
CREATE INDEX IF NOT EXISTS {{prefix}}sessions_user_id ON {{prefix}}sessions (user_id);
