-- M4: comments, media library, and navigation-menu support (PostgreSQL).

CREATE TABLE IF NOT EXISTS {{prefix}}comments (
  "comment_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comment_post_ID BIGINT NOT NULL DEFAULT 0,
  comment_author TEXT NOT NULL DEFAULT '',
  comment_author_email VARCHAR(100) NOT NULL DEFAULT '',
  comment_author_url VARCHAR(200) NOT NULL DEFAULT '',
  comment_author_IP VARCHAR(100) NOT NULL DEFAULT '',
  comment_date TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
  comment_date_gmt TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
  comment_content TEXT NOT NULL,
  comment_approved VARCHAR(20) NOT NULL DEFAULT '1',
  comment_agent VARCHAR(255) NOT NULL DEFAULT '',
  comment_parent BIGINT NOT NULL DEFAULT 0,
  user_id BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS {{prefix}}comments_post_id ON {{prefix}}comments (comment_post_ID);
CREATE INDEX IF NOT EXISTS {{prefix}}comments_approved_date_gmt ON {{prefix}}comments (comment_approved, comment_date_gmt);
CREATE INDEX IF NOT EXISTS {{prefix}}comments_date_gmt ON {{prefix}}comments (comment_date_gmt);
CREATE INDEX IF NOT EXISTS {{prefix}}comments_parent ON {{prefix}}comments (comment_parent);
CREATE INDEX IF NOT EXISTS {{prefix}}comments_author_email ON {{prefix}}comments (comment_author_email);
CREATE INDEX IF NOT EXISTS {{prefix}}comments_user_id ON {{prefix}}comments (user_id);

CREATE TABLE IF NOT EXISTS {{prefix}}commentmeta (
  meta_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comment_id BIGINT NOT NULL DEFAULT 0,
  meta_key VARCHAR(255) DEFAULT NULL,
  meta_value TEXT
);
CREATE INDEX IF NOT EXISTS {{prefix}}commentmeta_comment_id ON {{prefix}}commentmeta (comment_id);
CREATE INDEX IF NOT EXISTS {{prefix}}commentmeta_meta_key ON {{prefix}}commentmeta (meta_key);

ALTER TABLE {{prefix}}posts ADD COLUMN IF NOT EXISTS comment_status VARCHAR(20) NOT NULL DEFAULT 'open';
ALTER TABLE {{prefix}}posts ADD COLUMN IF NOT EXISTS post_parent BIGINT NOT NULL DEFAULT 0;
ALTER TABLE {{prefix}}posts ADD COLUMN IF NOT EXISTS post_mime_type VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE {{prefix}}posts ADD COLUMN IF NOT EXISTS menu_order INT NOT NULL DEFAULT 0;
